version: '3.8'
services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - ${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}
    networks:
      - react-spring
    depends_on:
      - backend

  backend:
    build:
      context: rest-service
      target: development
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./rest-service/:/app
    depends_on:
      - mysqlserver
    networks:
      - react-spring
      - spring-mysql

  mysqlserver:
    image: mysql:8.0
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - spring-mysql
volumes:
  mysql_data:
  mysql_config:
networks:
  react-spring:
  spring-mysql:
