version: '3.8'
services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    networks:
      - react-spring
    depends_on:
      - backend

  backend:
    build:
      context: rest-service
      target: development
    ports:
      - '8000:8000'
      - '8080:8080'
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - MYSQL_URL=${MYSQL_URL}
    volumes:
      - ./rest-service/:/app
    depends_on:
      - mysqlserver
    networks:
      - react-spring
      - spring-mysql

  mysqlserver:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - spring-mysql
volumes:
  mysql_data:
  mysql_config:
networks:
  react-spring:
  spring-mysql:
